name: Update index.yaml
on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    - name: Run auto-update script
      run: python Utilities/auto-update-index.py . index.yaml
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: Update index.yaml
        commit-message: Update index.yaml
        add-paths: index.yaml
        branch: update-index-yaml
        delete-branch: true
